spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/{vendor}